### ISSUE TITLE
run it inside k8s cluster

### ISSUE THREAD

**Issue by ciocan** [czhu12/canine#188]
I'm tring to run it inside the cluster with this config.
The web container keep restarting in an infinite loop.
I think it takes too long to complete db preparation or other tasks to finish and k8s see it as stuck or something and will restart. I'm junior at kubernetes and this is just an assumption.

I'm also confused about the purpose of the port 3200.

```yaml
---
# 1. Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: canine

---
# 2. Secret for web app env vars
apiVersion: v1
kind: Secret
metadata:
  name: canine-env
  namespace: canine
type: Opaque
stringData:
  # Used by the web Pod to connect to Postgres
  DATABASE_URL: "postgres://postgres:password@postgres:5432"
  # Used by the web Pod to connect to Redis
  REDIS_URL:    "redis://redis:6379"
  # Your app’s credentials
  CANINE_USERNAME: "canine"
  CANINE_PASSWORD: "test"

---
# 3. PostgreSQL StatefulSet (with dynamic PVC)
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: canine
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_MULTIPLE_DATABASES
              value: "canine_production,canine_development"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        storageClassName: local-path
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi

---
# 4. Postgres ClusterIP Service
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: canine
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432

---
# 5. Redis Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: canine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:alpine
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "512Mi"

---
# 6. Redis ClusterIP Service
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: canine
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379

---
# 7. Web Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: canine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      volumes:
        # to mount Docker socket inside the Pod
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock
      containers:
        - name: web
          image: ghcr.io/czhu12/canine:latest
          imagePullPolicy: IfNotPresent
          # pull all the secret'ed vars
          envFrom:
            - secretRef:
                name: canine-env
          # compose also set these
          env:
            - name: LOCAL_MODE
              value: "true"
            - name: PORT
              value: "3000"
            - name: APP_HOST
              value: "http://localhost:3000"
          ports:
            - containerPort: 3000
            - containerPort: 3200
          volumeMounts:
            - name: dockersock
              mountPath: /var/run/docker.sock
          resources:
            requests:
              cpu:    "2"
              memory: "512Mi"
            limits:
              cpu:    "4"
              memory: "2Gi"
---
# 8. Web Service (NodePort for external access)
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: canine
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 30001
    - name: aux
      port: 3200
      targetPort: 3200
      nodePort: 30002
```

**Comment by orefalo** [comment]
sounds like a healthcheck issue.

**Comment by orefalo** [comment]
The code is here - https://github.com/orefalo/canine_helm

**Comment by czhu12** [comment]
Oh nice! I'll take a look at this as soon as I finish the preview app feature

**Comment by akhan23wgu** [comment]
@orefalo This isn't an issue with Canine.sh. You're missing a few options in your helm chart. Your readiness probe is also wrong, it's trying to reach a URL that requires authentication, which is why the probe fails. The liveness probe has the same issue. See my diff below.

```diff
diff --git a/templates/deployment.yaml b/templates/deployment.yaml
index 3d48ab4..0e27f50 100644
--- a/templates/deployment.yaml
+++ b/templates/deployment.yaml
@@ -45,24 +45,19 @@ spec:
           {{- if .Values.volumes.dockerSocket.enabled }}
           volumeMounts:
             - name: dockersock
-              mountPath: /var/run/docker.sock
+              mountPath: {{ .Values.volumes.dockerSocket.hostPath }}
           {{- end }}
           livenessProbe:
-            httpGet:
-              path: /
+            tcpSocket:
+              port: http
               port: http
             initialDelaySeconds: 30
             periodSeconds: 10
-            timeoutSeconds: 5
-            failureThreshold: 3
           readinessProbe:
-            httpGet:
-              path: /
+            tcpSocket:
               port: http
             initialDelaySeconds: 10
             periodSeconds: 5
-            timeoutSeconds: 3
-            failureThreshold: 3
           {{- if .Values.resources }}
           resources:
             {{- toYaml .Values.resources | nindent 12 }}
diff --git a/templates/secret.yaml b/templates/secret.yaml
index 8b3d51b..f3ecf29 100644
--- a/templates/secret.yaml
+++ b/templates/secret.yaml
@@ -11,3 +11,4 @@ stringData:
   REDIS_URL: "redis://{{ include "canine.fullname" . }}-redis:6379"
   CANINE_USERNAME: {{ .Values.app.username | quote }}
   CANINE_PASSWORD: {{ .Values.app.password | quote }}
+  SECRET_KEY_BASE: {{ .Values.app.secretKey | quote }}
```

My working values file is below. I'm running containerd instead of docker on my k3s instance, so I changed the socket accordingly. I am also using MetalLB as my LoadBalancer to assign L2 addresses, so the service is set to LoadBalancer. I also pulled the latest sha of the docker container.

```yaml
app:
  port: "3456"
  username: "admin"
  password: "mysecret"
  host: "http://localhost:3456"
  localMode: true 
  secretKey: "mysecretkey"

postgresql:
  auth:
    username: "postgresql"
    password: "postgresql"

service:
  port: 3456
  type: LoadBalancer


image:
  repository: chriszhu12/canine
  tag: latest@sha256:b2dbc2e00c4cb3e3e6c79bec793652c158de50964da99bd587084789f81246ce

volumes:
  dockerSocket:
    hostPath: /var/run/k3s/containerd/containerd.sock
```
